FROM node as builder

RUN mkdir -p /home/FCU_LLM

WORKDIR /home/FCU_LLM

COPY . .

RUN npm i

RUN npm run build

FROM nginx

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /home/FCU_LLM /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]